# Concatenates data/*.json into data/data.js so the page can load talent data from file://
# without a webserver.

$ErrorActionPreference = 'Stop'
Set-Location (Split-Path -Parent $PSScriptRoot)

$classes = @('druid', 'hunter', 'mage', 'paladin', 'priest', 'rogue', 'shaman', 'warlock', 'warrior')

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// Generated by tool; do not edit by hand.')
[void]$sb.AppendLine('window.TALENT_DATA = {')

for ($i = 0; $i -lt $classes.Count; $i++) {
    $c = $classes[$i]
    $json = Get-Content "data\$c.json" -Raw
    [void]$sb.Append("  ""$c"": ")
    [void]$sb.Append($json.TrimEnd())
    if ($i -lt $classes.Count - 1) { [void]$sb.AppendLine(',') } else { [void]$sb.AppendLine() }
}

[void]$sb.AppendLine('};')

Set-Content -LiteralPath 'data\data.js' -Value $sb.ToString() -Encoding UTF8
Write-Host "Wrote data\data.js ($($sb.Length) bytes, $($classes.Count) classes)"
